[package]
name = "bfi"
version = "0.1.0"
authors = ["Gordon Hart <gordon.hart2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rustyline = "5.0.4"
